### PR TITLE
Issue #30: Compile PDF on push and PR creation

### PR DESCRIPTION
**Pull request by emilyperica**
﻿## GitHub Issue

Issue #30 

## Description
- Removed 'Reflection' directory as it is a duplicate of ReflectAndTrace
- Removed lines in docs/makefile causing errors

### CODE REVIEW

**Review by ianzachary — APPROVED** [review]

**Review by stoiyeet — COMMENTED** [review]
Can we add something like:
   paths:
      - '**/*.tex'
under the event trigger? Something so it only runs if a tex file has changed

**Comment by stoiyeet** [comment]
the YML LGTM. Is there any other files I should focus on, or no?

**Comment by emilyperica** [comment]
> the YML LGTM. Is there any other files I should focus on, or no?
> 
> Second thought. should it only be done on pushes to main? I think any branch with tex files should have the pdfs rendered, right?

All the other files are is just from running make locally. The pdfs shouldn't be rendered in a commit in a feature branch because it makes merging/rebasing really messy (I know ian and jackson were having trouble with that I'm not sure if you ran into it too). Ideally people aren't ever committing their pdfs and instead will just let the workflow do it for them, I haven't figured out a way yet to enforce that so it will just have to be by convention for now.

**Comment by stoiyeet** [comment]
> > the YML LGTM. Is there any other files I should focus on, or no?
> > Second thought. should it only be done on pushes to main? I think any branch with tex files should have the pdfs rendered, right?
> 
> All the other files are is just from running make locally. The pdfs shouldn't be rendered in a commit in a feature branch because it makes merging/rebasing really messy (I know ian and jackson were having trouble with that I'm not sure if you ran into it too). Ideally people aren't ever committing their pdfs and instead will just let the workflow do it for them, I haven't figured out a way yet to enforce that so it will just have to be by convention for now.

Second question, when we merge the PR, that counts as a push too, right? Idk how to check but I think it means that when we squash and merge the action will be triggered to make another commit on top of that (assuming it has permission). Maybe we should just trigger this by Pull Request instead?

**Comment by emilyperica** [comment]
> > > the YML LGTM. Is there any other files I should focus on, or no?
> > > Second thought. should it only be done on pushes to main? I think any branch with tex files should have the pdfs rendered, right?
> > 
> > 
> > All the other files are is just from running make locally. The pdfs shouldn't be rendered in a commit in a feature branch because it makes merging/rebasing really messy (I know ian and jackson were having trouble with that I'm not sure if you ran into it too). Ideally people aren't ever committing their pdfs and instead will just let the workflow do it for them, I haven't figured out a way yet to enforce that so it will just have to be by convention for now.
> 
> Second question, when we merge the PR, that counts as a push too, right? Idk how to check but I think it means that when we squash and merge the action will be triggered to make another commit on top of that (assuming it has permission). Maybe we should just trigger this by Pull Request instead?

Yes it will be an additional commit, this is intentional. If it's triggered on PR then it just does the exact same thing as if a person compiles the PDF in their own commit, which is the issue I'm trying to solve

**Review by JaakLipp — APPROVED** [review]
Looks good following the changes and your reasoning

**Pull request merged**
